import type { Metadata } from 'next'
import { ProofPage } from '@/components/marketing/proof-page'
import { resolveNavState } from '@/lib/marketing/nav-state'

export const dynamic = 'force-dynamic'
export const metadata: Metadata = { title: 'AnswerLoops Support Workflow — From Question to Knowledge', description: 'Walk one question from a community channel to a cited answer: the ticket it becomes, the sources the drafting agent pulls, the reviewer agent’s decision, and what your team promotes into knowledge afterward.', alternates: { canonical: '/support-workflow' } }

export default async function SupportWorkflowPage() {
  return <ProofPage navState={await resolveNavState()} eyebrow="Support workflow walkthrough" title="From community question to reusable answer" intro="A question your community already answered shouldn’t need a person to retype it. Here’s each step instead — source, ticket, evidence, the reviewer agent’s call, and what your team keeps — with nothing hidden." sections={[{ title: '1. A question arrives', body: 'A user asks for help in Discord, Slack, a Discourse or Circle forum, GitHub, email, Telegram, Google Chat, or the web widget. AnswerLoops records the request with its source channel and org.', details: ['Incoming messages are normalized into tickets', 'The original channel remains available to the team', 'Classification and priority help sort what needs attention'] }, { title: '2. Evidence is retrieved', body: 'The drafting agent searches the org’s knowledge and pulls the passages most relevant to the question.', details: ['The docs and knowledge articles it draws on are recorded with the draft', 'Repository content and prior resolved tickets feed technical questions', 'Claims without a source in the retrieved context don’t make the draft'] }, { title: '3. The answer is gated', body: 'The reviewer agent checks the draft against the sources it cited and scores its confidence.', details: ['Clears the bar: it posts in the channel the question came from', 'Below the bar: it routes to a teammate with the draft attached', 'Your team edits, answers, or escalates from one queue'] }, { title: '4. The resolution compounds', body: 'A resolved question isn’t just closed. When the answer is broadly useful, your team promotes it into the knowledge base.', details: ['The next draft can retrieve and cite it', 'The same question, asked again, is a one-step answer', 'The knowledge base grows from questions you actually received'] }]} docs={[{ label: 'Product introduction', href: '/docs/introduction' }, { label: 'Widget documentation', href: '/docs/product/widget' }, { label: 'MCP integration', href: '/docs/integrations/mcp' }]} schema={{ name: 'AnswerLoops support workflow', description: 'How AnswerLoops turns community questions into grounded, reviewed, reusable support answers.', path: '/support-workflow', breadcrumbs: [{ name: 'Proof', path: '/agentic-support' }] }} />
}
