import type { Metadata } from 'next'
import { ProofPage } from '@/components/marketing/proof-page'
import { resolveNavState } from '@/lib/marketing/nav-state'

export const dynamic = 'force-dynamic'
export const metadata: Metadata = { title: 'AnswerLoops Support Workflow — From Question to Knowledge', description: 'Follow a real AnswerLoops support workflow from an incoming community question to a grounded answer, human review, resolution, and reusable knowledge.', alternates: { canonical: '/support-workflow' } }

export default async function SupportWorkflowPage() {
  return <ProofPage navState={await resolveNavState()} eyebrow="Support workflow walkthrough" title="From community question to reusable answer" intro="The core workflow is deliberately visible: every question has a source, a ticket, retrieved evidence, an answer decision, and a resolution that your team can improve." sections={[{ title: '1. A question arrives', body: 'A user asks for help in Discord, GitHub, Slack, email, Telegram, Google Chat, or the web widget. AnswerLoops captures the request with its source and organization context.', details: ['Incoming messages are normalized into tickets', 'The original channel remains available to the team', 'Classification and priority help sort what needs attention'] }, { title: '2. Evidence is retrieved', body: 'The support pipeline searches the knowledge available to the organization and gathers the most relevant context for the request.', details: ['Relevant docs and knowledge articles are returned', 'Repository and prior support context can inform technical questions', 'The answer is tied to sources instead of unsupported general copy'] }, { title: '3. The answer is gated', body: 'AnswerLoops drafts a response and evaluates whether it is strong enough to post automatically.', details: ['High-confidence answers can go back to the originating channel', 'Low-confidence cases route to a human with a draft', 'The team can edit, answer, or escalate from one queue'] }, { title: '4. The resolution compounds', body: 'A resolved question is not just closed. When it is broadly useful, the answer can be promoted into the knowledge base for future visitors and community members.', details: ['Approved knowledge becomes available to later retrieval', 'Repeated questions become faster to resolve', 'The support system gets better from real community interactions'] }]} docs={[{ label: 'Product introduction', href: '/docs/introduction' }, { label: 'Widget documentation', href: '/docs/product/widget' }, { label: 'MCP integration', href: '/docs/integrations/mcp' }]} />
}
