import type { Metadata } from 'next'
import { ProofPage } from '@/components/marketing/proof-page'
import { resolveNavState } from '@/lib/marketing/nav-state'

export const dynamic = 'force-dynamic'
export const metadata: Metadata = { title: 'AnswerLoops Support Workflow — From Question to Knowledge', description: "Here's what actually happens between a community question coming in and an answer going out — what it's checked against, when a human gets pulled in, and how the answer becomes reusable knowledge.", alternates: { canonical: '/support-workflow' } }

export default async function SupportWorkflowPage() {
  return <ProofPage navState={await resolveNavState()} eyebrow="Support workflow walkthrough" title="From community question to reusable answer" intro="Nobody should have to retype an answer your community already gave. Here's the actual path a question takes: where it came from, what it's checked against, who decides if it's good enough, and what happens to the answer afterward. None of it's hidden." sections={[{ title: '1. A question arrives', body: "Somebody asks for help — in Discord, Slack, a forum, GitHub, email, Telegram, Google Chat, or your widget. AnswerLoops turns that into a ticket and keeps track of where it came from.", details: ['Incoming messages are normalized into tickets', 'The original channel remains available to the team', 'Classification and priority help sort what needs attention'] }, { title: '2. Evidence is retrieved', body: "It searches your docs, your knowledge base, and past tickets for whatever's actually relevant to the question.", details: ['Relevant docs and knowledge articles are returned', 'Repository and prior support context can inform technical questions', 'The answer is tied to sources instead of unsupported general copy'] }, { title: '3. The answer is gated', body: "The AnswerLoops agent drafts a reply. A second agent checks it against what was found and decides if it's good enough to send on its own.", details: ['High-confidence answers can go back to the originating channel', 'Low-confidence cases route to a human with a draft', 'The team can edit, answer, or escalate from one queue'] }, { title: '4. The resolution compounds', body: "Closing the question isn't the end. If the answer is useful beyond this one case, it gets added to the knowledge base — so next time, it's already there.", details: ['Approved knowledge becomes available to later retrieval', 'Repeated questions become faster to resolve', 'The support system gets better from real community interactions'] }]} docs={[{ label: 'Product introduction', href: '/docs/introduction' }, { label: 'Widget documentation', href: '/docs/product/widget' }, { label: 'MCP integration', href: '/docs/integrations/mcp' }]} schema={{ name: 'AnswerLoops support workflow', description: 'How a community question becomes a checked, reusable answer in AnswerLoops.', path: '/support-workflow', breadcrumbs: [{ name: 'Proof', path: '/agentic-support' }] }} />
}
