import type { Metadata } from 'next'
import { IntentPage } from '@/components/marketing/intent-page'
import { resolveNavState } from '@/lib/marketing/nav-state'

export const dynamic = 'force-dynamic'
export const metadata: Metadata = {
  title: 'MCP Support Agents for Customer Support — AnswerLoops',
  description: 'Give MCP-compatible agents grounded access to AnswerLoops knowledge, FAQs, tickets, and support answers through the same pipeline as your community channels.',
  alternates: { canonical: '/mcp-support-agents' },
}

export default async function McpSupportAgentsPage() {
  return <IntentPage navState={await resolveNavState()} eyebrow="MCP support agents" title="MCP support agents for customer support" intro="AnswerLoops gives MCP-compatible agents a controlled way to search support knowledge, read FAQs, create tickets, and generate grounded answers. Your agent gets support context without needing a second, disconnected knowledge system." audience="Teams building internal copilots, support automations, coding agents, or custom bots that need reliable customer-support context and an explicit write boundary." highlights={[{ title: 'Use the same support brain', body: 'MCP calls use the knowledge base, ticket context, and answer pipeline that power Discord, Slack, email, and web chat.' }, { title: 'Grounded answers on demand', body: 'Agents can search relevant knowledge and request an answer grounded in the sources available to the workspace.' }, { title: 'A narrow write surface', body: 'Create tickets when a human workflow is needed; agents do not change billing, settings, or the knowledge base through MCP.' }, { title: 'Works with agent tooling', body: 'Connect MCP-compatible clients such as Claude Code, Cursor, or your own agent to the documented endpoint.' }]} workflow={[{ step: '01', title: 'Connect', body: 'Create an API key with the appropriate workspace access and point your MCP client at the AnswerLoops endpoint.' }, { step: '02', title: 'Retrieve', body: 'Search the knowledge base, read FAQs, list tickets, or ask for a grounded answer using structured tools.' }, { step: '03', title: 'Escalate', body: 'Create a ticket when the agent cannot safely resolve the request, leaving the support team a clear trail to review.' }]} comparison={[{ question: 'What can an agent do?', answer: 'Search knowledge, retrieve FAQs, list tickets, create tickets, and generate grounded answers through the documented MCP tools.' }, { question: 'Is MCP separate from channel support?', answer: 'No. MCP uses the same support pipeline and workspace knowledge as the channel integrations.' }, { question: 'Where is the endpoint?', answer: 'The MCP endpoint is documented at `/api/mcp`, with setup and tool details in the MCP integration guide.' }]} docs={[{ label: 'Read the MCP guide', href: '/docs/integrations/mcp' }, { label: 'Agent API reference', href: '/docs/integrations/agent-api' }, { label: 'See the support loop', href: '/agentic-support' }]} />
}
