import type { Metadata } from 'next'
import { IntentPage } from '@/components/marketing/intent-page'
import { resolveNavState } from '@/lib/marketing/nav-state'

export const dynamic = 'force-dynamic'
export const metadata: Metadata = {
  title: 'Self-Hosted AI Support Platform — AnswerLoops',
  description: 'Run AnswerLoops as a self-hosted AI support platform with Docker Compose, your own infrastructure, your own model provider, and your own data controls.',
  alternates: { canonical: '/self-hosted-ai-support' },
}

export default async function SelfHostedAiSupportPage() {
  return <IntentPage navState={await resolveNavState()} eyebrow="Self-hosted AI support" title="What is a self-hosted AI support platform?" intro="A self-hosted AI support platform runs the support application, data, and automation under your control. AnswerLoops gives developer communities that deployment option without giving up grounded answers, channel integrations, or human review." audience="Engineering-led teams, open-source projects, and organizations that need control over deployment, data location, model credentials, or network access." highlights={[{ title: 'Deploy with Docker Compose', body: 'Start from the documented Compose setup and keep the app, bot, database, and configuration in an environment you control.' }, { title: 'Bring your own model provider', body: 'Choose the model provider and credentials that fit your budget, compliance requirements, and latency needs.' }, { title: 'Keep support data close', body: 'Tickets, connected knowledge, and configuration stay within the deployment boundary you choose.' }, { title: 'No hosted lock-in', body: 'Use the managed service for convenience or self-host the open-source project when operational control matters more.' }]} workflow={[{ step: '01', title: 'Prepare', body: 'Clone the project, configure the required services and OAuth credentials, and choose where the deployment will run.' }, { step: '02', title: 'Connect', body: 'Attach Discord, Slack, GitHub, email, or web chat, then seed the knowledge base with docs and repository content.' }, { step: '03', title: 'Operate', body: 'Let the confidence-gated pipeline answer repeat questions while your team reviews the cases that need judgment.' }]} comparison={[{ question: 'What license is it?', answer: 'AnswerLoops is open source under AGPL-3.0. Review the repository and deployment documentation before operating it.' }, { question: 'What does self-hosting include?', answer: 'The application, bot services, database connection, integrations, and AI configuration run as part of your deployment.' }, { question: 'Where do I start?', answer: 'Follow the self-host quickstart, then use the provider-specific deployment and integration guides.' }]} docs={[{ label: 'Self-host quickstart', href: '/docs/quickstart-self-host' }, { label: 'Docker deployment', href: '/docs/self-hosting/docker' }, { label: 'Environment variables', href: '/docs/self-hosting/environment-variables' }]} schema={{ name: 'What is a self-hosted AI support platform?', description: 'How AnswerLoops supports self-hosted AI support deployments.', path: '/self-hosted-ai-support', breadcrumbs: [{ name: 'Support', path: '/agentic-support' }] }} />
}
