import type { Metadata } from 'next'
import { IntentPage } from '@/components/marketing/intent-page'
import { resolveNavState } from '@/lib/marketing/nav-state'

export const dynamic = 'force-dynamic'
export const metadata: Metadata = {
  title: 'Open-Source Community Support — AnswerLoops',
  description: 'A question already answered in your docs or three threads back in Discord gets asked again. AnswerLoops drafts the answer from your docs, repo, and resolved issues, a second agent checks it, and it posts in the same Discord, GitHub, or Slack thread. Maintainers only see what the check couldn’t clear.',
  alternates: { canonical: '/open-source-support' },
}

export default async function OpenSourceSupportPage() {
  return <IntentPage navState={await resolveNavState()} eyebrow="Open-source community support" title="Open-source community support, answered in your community channel" intro="Someone opens a GitHub issue asking something already answered in the docs, or three threads back in Discord. AnswerLoops finds that answer and posts it back in the same Discord, GitHub, or Slack thread it came from, so a repeat question stops being another interruption for the core team." audience="Open-source maintainers, developer-relations teams, and community operators whose users ask for help in public channels instead of a traditional support inbox." highlights={[{ title: 'Meet users where they ask', body: 'Discord, GitHub Issues and Discussions, Slack, Telegram, email, and the web widget all feed one ticket-and-answer workflow with one knowledge base.' }, { title: 'Keep answers grounded', body: 'The drafting agent searches your docs, connected repositories, and approved knowledge first — and cites what it used.' }, { title: 'Protect maintainer time', body: 'The reviewer agent clears repeat answers to post on their own; anything it can’t clear stays in the queue with the draft attached.' }, { title: 'Let the community teach the system', body: 'Promote a resolved answer into the knowledge base and the next time that question comes up, the draft can cite it.' }]} workflow={[{ step: '01', title: 'Collect', body: 'A question lands in the channel your community already uses and becomes a ticket with its source attached.' }, { step: '02', title: 'Ground', body: 'The drafting agent writes an answer from your docs and knowledge; the reviewer agent checks it against those sources before it posts.' }, { step: '03', title: 'Improve', body: 'Your team handles what the reviewer couldn’t clear and promotes the good answers into the knowledge base.' }]} comparison={[{ question: 'Is it open source?', answer: 'Yes. The project is available under AGPL-3.0 and can be run on your own infrastructure.' }, { question: 'Who is it for?', answer: 'Open-source projects and the communities around them, especially where Discord, a forum, and GitHub are the primary support surfaces.' }, { question: 'Does it replace maintainers?', answer: 'No. It answers the repeatable questions and routes uncertain or sensitive ones to a person, draft in hand.' }]} docs={[{ label: 'Read the introduction', href: '/docs/introduction' }, { label: 'Self-host it', href: '/docs/quickstart-self-host' }, { label: 'See pricing', href: '/pricing' }]} schema={{ name: 'Open-source community support', description: 'AnswerLoops support workflow for open-source maintainers and the communities around their projects.', path: '/open-source-support', breadcrumbs: [{ name: 'Support', path: '/agentic-support' }] }} />
}
