import { describe, it, expect } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'

/**
 * The docs source has to be generated before the build, explicitly.
 *
 * `.source/` is fumadocs-mdx codegen and is gitignored, so it does not exist on
 * a clean checkout. `next build` resolves `@/.source/server` while fumadocs is
 * still writing it, so the *first* build after a fresh clone fails with
 * "module not found" and every later build on the same machine succeeds — the
 * generated directory is still lying around.
 *
 * That is the worst possible shape for a deploy bug. It never reproduces
 * locally, because nobody's laptop is ever a clean checkout twice. CI missed it
 * too, but for a different reason worth remembering: `pnpm test` runs before
 * `pnpm build` there, and the test run generates `.source` as a side effect. CI
 * was green because of the order its steps happen to be in, not because the
 * build works.
 *
 * A platform that checks out fresh for every deploy — Railway does — hits the
 * failing path every single time.
 */

const read = (rel: string) => fs.readFileSync(path.join(process.cwd(), rel), 'utf-8')

describe('the generated docs source', () => {
  const scripts = () => JSON.parse(read('package.json')).scripts as Record<string, string>

  it('is generated by an explicit prebuild step, not as a side effect', () => {
    const s = scripts()
    expect(s.prebuild, 'no prebuild step — the first build on a clean checkout fails').toBeTruthy()
    expect(s.prebuild).toContain('fumadocs-mdx')
  })

  it('runs before build, which is the whole point of the name', () => {
    // npm/pnpm lifecycle: `prebuild` runs automatically before `build`. If the
    // build script were ever renamed, this pairing silently stops applying.
    const s = scripts()
    expect(s.build).toContain('next build')
    expect(Object.keys(s)).toContain('prebuild')
  })

  it('is actually depended on, so this is not a precaution against nothing', () => {
    // If the import ever stops existing, the prebuild step can go too — but
    // while it exists, the build genuinely cannot start without the codegen.
    expect(read('lib/docs/source.ts')).toContain('@/.source/server')
  })

  it('stays out of version control, so it cannot go stale', () => {
    // Committing the generated output would fix the build for the wrong
    // reason and then drift from content/docs.
    expect(read('.gitignore')).toContain('/.source/')
  })
})
