import type { Metadata } from 'next'
import { ProofPage } from '@/components/marketing/proof-page'
import { resolveNavState } from '@/lib/marketing/nav-state'

export const dynamic = 'force-dynamic'
export const metadata: Metadata = { title: 'AnswerLoops Architecture — Support Pipeline and Knowledge Loop', description: 'See how AnswerLoops connects community channels, knowledge retrieval, confidence review, human escalation, and reusable support knowledge.', alternates: { canonical: '/architecture' } }

export default async function ArchitecturePage() {
  return <ProofPage navState={await resolveNavState()} eyebrow="Architecture overview" title="A support pipeline built around evidence and review" intro="AnswerLoops turns questions from community channels into a structured workflow: ingest the request, retrieve relevant knowledge, review the draft, respond in context, and preserve useful answers for next time." sections={[{ title: 'Channels become one ticket model', body: 'Discord, Slack, Discourse, Circle, GitHub, Telegram, email, and website chat can all start the same org-scoped support workflow.', details: ['Channel context stays attached to the ticket', 'Triage and prioritization are shared across sources', 'Teams can add channels without creating separate support brains'] }, { title: 'Knowledge retrieval grounds the draft', body: 'The answer pipeline searches the workspace knowledge available for the request before it produces a response.', details: ['Documentation and knowledge-base articles can be indexed', 'Connected repositories and approved sources add technical context', 'The website widget uses published knowledge for anonymous visitors'] }, { title: 'Confidence review controls automation', body: 'A separate review pass grades the draft before an answer is posted, so automation has an explicit quality gate.', details: ['High-confidence answers can be sent automatically', 'Uncertain questions stay in the human queue', 'Reviewers receive the question context and editable draft'] }, { title: 'Resolution creates a learning loop', body: 'When a team resolves a question, the useful answer can become reusable knowledge instead of disappearing into a closed ticket.', details: ['Resolved answers can be promoted into the knowledge base', 'Future questions can retrieve the approved explanation', 'The system improves from the support work your team already does'] }]} docs={[{ label: 'Product introduction', href: '/docs/introduction' }, { label: 'Self-host quickstart', href: '/docs/quickstart-self-host' }, { label: 'MCP integration', href: '/docs/integrations/mcp' }]} schema={{ name: 'AnswerLoops architecture', description: 'AnswerLoops support pipeline architecture and knowledge loop.', path: '/architecture', breadcrumbs: [{ name: 'Proof', path: '/agentic-support' }] }} />
}
